GET http://localhost:3000/users

###

POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "Fedor",
  "email": "Fedya@mail.ru",
  "password": "password"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "Nikita",
  "password": "passwor"
}